name: Main Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    secrets: inherit